name: 'Browserslist: Regex'

on:
  schedule:
    - cron: '0 0 * * 2' # Every Tuesday at 00:00 AM UTC on the default branch
  workflow_dispatch:

jobs:
  browserslist-regex:
    uses: dargmuesli/github-actions/.github/workflows/browserslist-regex.yml@0.16.18
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      CACHE_PATH: nuxt/yarn.lock
      DIRECTORY: nuxt/
      NODE_VERSION: 16
      OUTPUT_PATH: supportedBrowsers.js
