name: 'Release: Scheduled'

on:
  schedule:
    - cron:  '0 0 * * 1' # Every Monday at 00:00 AM UTC on the default branch

jobs:
  release-schedule:
    name: 'Release: Scheduled'
    uses: dargmuesli/github-actions/.github/workflows/release-schedule.yml@0.4.0
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      PACKAGE_JSON_PATH: 'nuxt/package.json'
